# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pointing_stability.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1043, 780)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 981, 631))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_microView = QtWidgets.QWidget()
        self.tab_microView.setObjectName("tab_microView")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_microView)
        self.formLayoutWidget.setGeometry(QtCore.QRect(740, 40, 221, 273))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.btn_load_IR = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_load_IR.setObjectName("btn_load_IR")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.btn_load_IR)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.le_cam1_exp_time = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_cam1_exp_time.setObjectName("le_cam1_exp_time")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_cam1_exp_time)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.le_cam1_gain = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_cam1_gain.setObjectName("le_cam1_gain")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_cam1_gain)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_17)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.cb_cam1 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cb_cam1.setEditable(False)
        self.cb_cam1.setObjectName("cb_cam1")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cb_cam1)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.le_cam1_threshold = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_cam1_threshold.setObjectName("le_cam1_threshold")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.le_cam1_threshold)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.Cam1_AvgFrames = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.Cam1_AvgFrames.setObjectName("Cam1_AvgFrames")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.Cam1_AvgFrames)
        self.btn_cam1_gen_ROI = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_cam1_gen_ROI.setObjectName("btn_cam1_gen_ROI")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.btn_cam1_gen_ROI)
        self.btn_cam1_apply_ROI = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_cam1_apply_ROI.setObjectName("btn_cam1_apply_ROI")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.btn_cam1_apply_ROI)
        self.btn_cam1_update = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_cam1_update.setObjectName("btn_cam1_update")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.btn_cam1_update)
        self.btn_load_visible = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_load_visible.setObjectName("btn_load_visible")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.btn_load_visible)
        self.gv_camera2 = ImageView(self.tab_microView)
        self.gv_camera2.setGeometry(QtCore.QRect(10, 310, 701, 281))
        self.gv_camera2.setObjectName("gv_camera2")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab_microView)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(740, 320, 221, 232))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.le_cam2_exp_time = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.le_cam2_exp_time.setObjectName("le_cam2_exp_time")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_cam2_exp_time)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.le_cam2_gain = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.le_cam2_gain.setObjectName("le_cam2_gain")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_cam2_gain)
        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.label_19 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_19)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.cb_cam2 = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.cb_cam2.setEditable(False)
        self.cb_cam2.setObjectName("cb_cam2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cb_cam2)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.le_cam2_threshold = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.le_cam2_threshold.setObjectName("le_cam2_threshold")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.le_cam2_threshold)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.Cam2_AvgFrames = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.Cam2_AvgFrames.setObjectName("Cam2_AvgFrames")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.Cam2_AvgFrames)
        self.btn_cam2_update = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.btn_cam2_update.setObjectName("btn_cam2_update")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.btn_cam2_update)
        self.btn_cam2_gen_ROI = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.btn_cam2_gen_ROI.setObjectName("btn_cam2_gen_ROI")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.btn_cam2_gen_ROI)
        self.btn_cam2_apply_ROI = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.btn_cam2_apply_ROI.setObjectName("btn_cam2_apply_ROI")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.btn_cam2_apply_ROI)
        self.gv_camera1 = ImageView(self.tab_microView)
        self.gv_camera1.setGeometry(QtCore.QRect(10, 10, 701, 281))
        self.gv_camera1.setObjectName("gv_camera1")
        self.layoutWidget = QtWidgets.QWidget(self.tab_microView)
        self.layoutWidget.setGeometry(QtCore.QRect(790, 540, 131, 24))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.le_cam2_max = QtWidgets.QLineEdit(self.layoutWidget)
        self.le_cam2_max.setReadOnly(True)
        self.le_cam2_max.setObjectName("le_cam2_max")
        self.horizontalLayout_2.addWidget(self.le_cam2_max)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_microView)
        self.layoutWidget1.setGeometry(QtCore.QRect(790, 260, 131, 24))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.le_cam1_max = QtWidgets.QLineEdit(self.layoutWidget1)
        self.le_cam1_max.setReadOnly(True)
        self.le_cam1_max.setObjectName("le_cam1_max")
        self.horizontalLayout.addWidget(self.le_cam1_max)
        self.cb_SystemSelection = QtWidgets.QComboBox(self.tab_microView)
        self.cb_SystemSelection.setGeometry(QtCore.QRect(780, 0, 141, 21))
        self.cb_SystemSelection.setObjectName("cb_SystemSelection")
        self.cb_SystemSelection.addItem("")
        self.cb_SystemSelection.addItem("")
        self.cb_SystemSelection.addItem("")
        self.pb_cam2_img_cap = QtWidgets.QPushButton(self.tab_microView)
        self.pb_cam2_img_cap.setGeometry(QtCore.QRect(800, 570, 101, 23))
        self.pb_cam2_img_cap.setObjectName("pb_cam2_img_cap")
        self.pb_cam1_img_cap = QtWidgets.QPushButton(self.tab_microView)
        self.pb_cam1_img_cap.setGeometry(QtCore.QRect(800, 290, 101, 23))
        self.pb_cam1_img_cap.setObjectName("pb_cam1_img_cap")
        self.tabWidget.addTab(self.tab_microView, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gv_cam_xy = GraphicsLayoutWidget(self.tab_2)
        self.gv_cam_xy.setGeometry(QtCore.QRect(20, 10, 701, 581))
        self.gv_cam_xy.setObjectName("gv_cam_xy")
        self.btn_clear = QtWidgets.QPushButton(self.tab_2)
        self.btn_clear.setGeometry(QtCore.QRect(760, 20, 93, 28))
        self.btn_clear.setObjectName("btn_clear")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(760, 60, 141, 31))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.le_num_points = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.le_num_points.setReadOnly(False)
        self.le_num_points.setObjectName("le_num_points")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_num_points)
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.tab_2)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(760, 120, 160, 125))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_cam1_dx_std = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_cam1_dx_std.setObjectName("label_cam1_dx_std")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_cam1_dx_std)
        self.label_cam1_dy_std = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_cam1_dy_std.setObjectName("label_cam1_dy_std")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_cam1_dy_std)
        self.label_cam2_dx_std = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_cam2_dx_std.setObjectName("label_cam2_dx_std")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_cam2_dx_std)
        self.label_cam2_dy_std = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_cam2_dy_std.setObjectName("label_cam2_dy_std")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_cam2_dy_std)
        self.le_cam1_dx_std = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.le_cam1_dx_std.setReadOnly(True)
        self.le_cam1_dx_std.setObjectName("le_cam1_dx_std")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_cam1_dx_std)
        self.le_cam1_dy_std = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.le_cam1_dy_std.setReadOnly(True)
        self.le_cam1_dy_std.setObjectName("le_cam1_dy_std")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_cam1_dy_std)
        self.le_cam2_dx_std = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.le_cam2_dx_std.setReadOnly(True)
        self.le_cam2_dx_std.setObjectName("le_cam2_dx_std")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_cam2_dx_std)
        self.le_cam2_dy_std = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.le_cam2_dy_std.setReadOnly(True)
        self.le_cam2_dy_std.setObjectName("le_cam2_dy_std")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.le_cam2_dy_std)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(760, 250, 169, 158))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_22.setObjectName("label_22")
        self.verticalLayout.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_23.setObjectName("label_23")
        self.verticalLayout.addWidget(self.label_23)
        self.le_data_acquisition_time = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.le_data_acquisition_time.setObjectName("le_data_acquisition_time")
        self.verticalLayout.addWidget(self.le_data_acquisition_time)
        self.cb_acquire_pointing = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.cb_acquire_pointing.setChecked(True)
        self.cb_acquire_pointing.setObjectName("cb_acquire_pointing")
        self.verticalLayout.addWidget(self.cb_acquire_pointing)
        self.cb_acquire_video = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.cb_acquire_video.setChecked(True)
        self.cb_acquire_video.setObjectName("cb_acquire_video")
        self.verticalLayout.addWidget(self.cb_acquire_video)
        self.cb_acquire_voltages = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.cb_acquire_voltages.setChecked(True)
        self.cb_acquire_voltages.setObjectName("cb_acquire_voltages")
        self.verticalLayout.addWidget(self.cb_acquire_voltages)
        self.btn_begin_acquisition = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_begin_acquisition.setObjectName("btn_begin_acquisition")
        self.verticalLayout.addWidget(self.btn_begin_acquisition)
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(-80, 830, 47, 13))
        self.label_21.setObjectName("label_21")
        self.formLayoutWidget_7 = QtWidgets.QWidget(self.tab_2)
        self.formLayoutWidget_7.setGeometry(QtCore.QRect(760, 460, 191, 131))
        self.formLayoutWidget_7.setObjectName("formLayoutWidget_7")
        self.formLayout_7 = QtWidgets.QFormLayout(self.formLayoutWidget_7)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_fps_t_avg = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.label_fps_t_avg.setObjectName("label_fps_t_avg")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_fps_t_avg)
        self.le_cam_fps_t_avg = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.le_cam_fps_t_avg.setReadOnly(False)
        self.le_cam_fps_t_avg.setObjectName("le_cam_fps_t_avg")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_cam_fps_t_avg)
        self.label_cam1_fps_read = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.label_cam1_fps_read.setObjectName("label_cam1_fps_read")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_cam1_fps_read)
        self.le_cam1_fps_read = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.le_cam1_fps_read.setReadOnly(True)
        self.le_cam1_fps_read.setObjectName("le_cam1_fps_read")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_cam1_fps_read)
        self.label_cam1_fps_processed = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.label_cam1_fps_processed.setObjectName("label_cam1_fps_processed")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_cam1_fps_processed)
        self.le_cam1_fps_processed = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.le_cam1_fps_processed.setReadOnly(True)
        self.le_cam1_fps_processed.setObjectName("le_cam1_fps_processed")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_cam1_fps_processed)
        self.label_cam2_fps_read = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.label_cam2_fps_read.setObjectName("label_cam2_fps_read")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_cam2_fps_read)
        self.le_cam2_fps_read = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.le_cam2_fps_read.setReadOnly(True)
        self.le_cam2_fps_read.setObjectName("le_cam2_fps_read")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.le_cam2_fps_read)
        self.label_cam2_fps_processed = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.label_cam2_fps_processed.setObjectName("label_cam2_fps_processed")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_cam2_fps_processed)
        self.le_cam2_fps_processed = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.le_cam2_fps_processed.setReadOnly(True)
        self.le_cam2_fps_processed.setObjectName("le_cam2_fps_processed")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.le_cam2_fps_processed)
        self.formLayoutWidget_9 = QtWidgets.QWidget(self.tab_2)
        self.formLayoutWidget_9.setGeometry(QtCore.QRect(730, 420, 245, 41))
        self.formLayoutWidget_9.setObjectName("formLayoutWidget_9")
        self.formLayout_10 = QtWidgets.QFormLayout(self.formLayoutWidget_9)
        self.formLayout_10.setContentsMargins(0, 0, 0, 0)
        self.formLayout_10.setObjectName("formLayout_10")
        self.label_processed_def = QtWidgets.QLabel(self.formLayoutWidget_9)
        self.label_processed_def.setObjectName("label_processed_def")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_processed_def)
        self.label_read_def = QtWidgets.QLabel(self.formLayoutWidget_9)
        self.label_read_def.setObjectName("label_read_def")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.label_read_def)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gv_piezo = GraphicsLayoutWidget(self.tab)
        self.gv_piezo.setGeometry(QtCore.QRect(20, 10, 701, 581))
        self.gv_piezo.setObjectName("gv_piezo")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(740, 10, 160, 88))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_12.setObjectName("label_12")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.cb_motors_1 = QtWidgets.QComboBox(self.formLayoutWidget_4)
        self.cb_motors_1.setObjectName("cb_motors_1")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cb_motors_1)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_13.setObjectName("label_13")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.cb_motors_2 = QtWidgets.QComboBox(self.formLayoutWidget_4)
        self.cb_motors_2.setObjectName("cb_motors_2")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cb_motors_2)
        self.btn_motor_connect = QtWidgets.QPushButton(self.formLayoutWidget_4)
        self.btn_motor_connect.setObjectName("btn_motor_connect")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btn_motor_connect)
        self.formLayoutWidget_6 = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(740, 150, 161, 111))
        self.formLayoutWidget_6.setObjectName("formLayoutWidget_6")
        self.formLayout_6 = QtWidgets.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.P = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.P.setObjectName("P")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.P)
        self.le_P = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.le_P.setObjectName("le_P")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_P)
        self.Ti = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.Ti.setObjectName("Ti")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Ti)
        self.Ti_2 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.Ti_2.setObjectName("Ti_2")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Ti_2)
        self.le_Td = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.le_Td.setObjectName("le_Td")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_Td)
        self.btn_PID_update = QtWidgets.QPushButton(self.formLayoutWidget_6)
        self.btn_PID_update.setObjectName("btn_PID_update")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.btn_PID_update)
        self.le_Ti = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.le_Ti.setObjectName("le_Ti")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_Ti)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(740, 270, 163, 321))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_24.setWordWrap(True)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_2.addWidget(self.label_24)
        self.cb_control_motor_1 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.cb_control_motor_1.setObjectName("cb_control_motor_1")
        self.verticalLayout_2.addWidget(self.cb_control_motor_1)
        self.cb_control_motor_2 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.cb_control_motor_2.setObjectName("cb_control_motor_2")
        self.verticalLayout_2.addWidget(self.cb_control_motor_2)
        self.cb_control_motor_3 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.cb_control_motor_3.setObjectName("cb_control_motor_3")
        self.verticalLayout_2.addWidget(self.cb_control_motor_3)
        self.cb_control_motor_4 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.cb_control_motor_4.setObjectName("cb_control_motor_4")
        self.verticalLayout_2.addWidget(self.cb_control_motor_4)
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_25.setWordWrap(True)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_2.addWidget(self.label_25)
        self.cb_slow_motor_1 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.cb_slow_motor_1.setObjectName("cb_slow_motor_1")
        self.verticalLayout_2.addWidget(self.cb_slow_motor_1)
        self.cb_slow_motor_2 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.cb_slow_motor_2.setObjectName("cb_slow_motor_2")
        self.verticalLayout_2.addWidget(self.cb_slow_motor_2)
        self.label_26 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_26.setWordWrap(True)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_2.addWidget(self.label_26)
        self.pb_update_control_motors = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pb_update_control_motors.setObjectName("pb_update_control_motors")
        self.verticalLayout_2.addWidget(self.pb_update_control_motors)
        self.formLayoutWidget_8 = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget_8.setGeometry(QtCore.QRect(740, 110, 161, 22))
        self.formLayoutWidget_8.setObjectName("formLayoutWidget_8")
        self.formLayout_9 = QtWidgets.QFormLayout(self.formLayoutWidget_8)
        self.formLayout_9.setContentsMargins(0, 0, 0, 0)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_piezo_updates_per_second = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.label_piezo_updates_per_second.setObjectName("label_piezo_updates_per_second")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_piezo_updates_per_second)
        self.le_piezo_updates_per_s = QtWidgets.QLineEdit(self.formLayoutWidget_8)
        self.le_piezo_updates_per_s.setText("")
        self.le_piezo_updates_per_s.setReadOnly(True)
        self.le_piezo_updates_per_s.setObjectName("le_piezo_updates_per_s")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_piezo_updates_per_s)
        self.tabWidget.addTab(self.tab, "")
        self.UnlockReport = QtWidgets.QWidget()
        self.UnlockReport.setObjectName("UnlockReport")
        self.list_unlock_report = QtWidgets.QListWidget(self.UnlockReport)
        self.list_unlock_report.setGeometry(QtCore.QRect(130, 20, 751, 192))
        self.list_unlock_report.setObjectName("list_unlock_report")
        self.label_unlock_report = QtWidgets.QLabel(self.UnlockReport)
        self.label_unlock_report.setGeometry(QtCore.QRect(130, 250, 751, 311))
        self.label_unlock_report.setWordWrap(True)
        self.label_unlock_report.setObjectName("label_unlock_report")
        self.tabWidget.addTab(self.UnlockReport, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.btn_lock = QtWidgets.QPushButton(self.centralwidget)
        self.btn_lock.setGeometry(QtCore.QRect(30, 660, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_lock.setFont(font)
        self.btn_lock.setCheckable(True)
        self.btn_lock.setObjectName("btn_lock")
        self.btn_Home = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Home.setGeometry(QtCore.QRect(180, 660, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_Home.setFont(font)
        self.btn_Home.setObjectName("btn_Home")
        self.btn_Align = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Align.setGeometry(QtCore.QRect(330, 660, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_Align.setFont(font)
        self.btn_Align.setObjectName("btn_Align")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(9, 9, 1021, 721))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1019, 719))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.cb_suppress_image_update = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.cb_suppress_image_update.setGeometry(QtCore.QRect(710, 650, 161, 17))
        self.cb_suppress_image_update.setObjectName("cb_suppress_image_update")
        self.cb_suppress_piezzo_update = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.cb_suppress_piezzo_update.setGeometry(QtCore.QRect(710, 670, 161, 17))
        self.cb_suppress_piezzo_update.setObjectName("cb_suppress_piezzo_update")
        self.cb_suppress_pointing_updat = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.cb_suppress_pointing_updat.setGeometry(QtCore.QRect(710, 690, 161, 17))
        self.cb_suppress_pointing_updat.setObjectName("cb_suppress_pointing_updat")
        self.cb_force_unlock = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.cb_force_unlock.setGeometry(QtCore.QRect(589, 680, 91, 17))
        self.cb_force_unlock.setChecked(True)
        self.cb_force_unlock.setObjectName("cb_force_unlock")
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_20.setGeometry(QtCore.QRect(450, 650, 131, 71))
        self.label_20.setWordWrap(True)
        self.label_20.setObjectName("label_20")
        self.le_max_unlock_time = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.le_max_unlock_time.setGeometry(QtCore.QRect(590, 650, 108, 20))
        self.le_max_unlock_time.setObjectName("le_max_unlock_time")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea.raise_()
        self.tabWidget.raise_()
        self.btn_lock.raise_()
        self.btn_Home.raise_()
        self.btn_Align.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1043, 21))
        self.menubar.setObjectName("menubar")
        self.menuCalibrate = QtWidgets.QMenu(self.menubar)
        self.menuCalibrate.setObjectName("menuCalibrate")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.act_calibrate = QtWidgets.QAction(MainWindow)
        self.act_calibrate.setObjectName("act_calibrate")
        self.actionLoad_Old_Home = QtWidgets.QAction(MainWindow)
        self.actionLoad_Old_Home.setObjectName("actionLoad_Old_Home")
        self.actionSave_State = QtWidgets.QAction(MainWindow)
        self.actionSave_State.setObjectName("actionSave_State")
        self.actionLoad_State = QtWidgets.QAction(MainWindow)
        self.actionLoad_State.setObjectName("actionLoad_State")
        self.menuCalibrate.addAction(self.act_calibrate)
        self.menuCalibrate.addAction(self.actionLoad_Old_Home)
        self.menuCalibrate.addAction(self.actionSave_State)
        self.menuCalibrate.addAction(self.actionLoad_State)
        self.menubar.addAction(self.menuCalibrate.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.gv_camera1, self.gv_cam_xy)
        MainWindow.setTabOrder(self.gv_cam_xy, self.gv_piezo)
        MainWindow.setTabOrder(self.gv_piezo, self.le_cam1_exp_time)
        MainWindow.setTabOrder(self.le_cam1_exp_time, self.le_cam1_gain)
        MainWindow.setTabOrder(self.le_cam1_gain, self.cb_cam1)
        MainWindow.setTabOrder(self.cb_cam1, self.le_cam1_threshold)
        MainWindow.setTabOrder(self.le_cam1_threshold, self.btn_cam1_update)
        MainWindow.setTabOrder(self.btn_cam1_update, self.le_cam1_max)
        MainWindow.setTabOrder(self.le_cam1_max, self.le_cam2_exp_time)
        MainWindow.setTabOrder(self.le_cam2_exp_time, self.le_cam2_gain)
        MainWindow.setTabOrder(self.le_cam2_gain, self.cb_cam2)
        MainWindow.setTabOrder(self.cb_cam2, self.le_cam2_threshold)
        MainWindow.setTabOrder(self.le_cam2_threshold, self.btn_cam2_update)
        MainWindow.setTabOrder(self.btn_cam2_update, self.le_cam2_max)
        MainWindow.setTabOrder(self.le_cam2_max, self.gv_camera2)
        MainWindow.setTabOrder(self.gv_camera2, self.btn_clear)
        MainWindow.setTabOrder(self.btn_clear, self.le_num_points)
        MainWindow.setTabOrder(self.le_num_points, self.cb_motors_1)
        MainWindow.setTabOrder(self.cb_motors_1, self.cb_motors_2)
        MainWindow.setTabOrder(self.cb_motors_2, self.tabWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mightex Camera"))
        self.btn_load_IR.setText(_translate("MainWindow", "Load Recent IR"))
        self.label.setText(_translate("MainWindow", "Exposure Time (ms)"))
        self.le_cam1_exp_time.setText(_translate("MainWindow", "0.05"))
        self.label_2.setText(_translate("MainWindow", "Gain (floating)"))
        self.le_cam1_gain.setText(_translate("MainWindow", "1"))
        self.label_16.setText(_translate("MainWindow", "fpa temp [C] 68=Dmg"))
        self.label_17.setText(_translate("MainWindow", "fpa temp [C]"))
        self.label_3.setText(_translate("MainWindow", "Select Camera"))
        self.label_7.setText(_translate("MainWindow", "Threshold"))
        self.le_cam1_threshold.setText(_translate("MainWindow", "0"))
        self.label_14.setText(_translate("MainWindow", "# of Frames 2 Avg"))
        self.Cam1_AvgFrames.setText(_translate("MainWindow", "1"))
        self.btn_cam1_gen_ROI.setText(_translate("MainWindow", "Generate ROI"))
        self.btn_cam1_apply_ROI.setText(_translate("MainWindow", "Crop to ROI"))
        self.btn_cam1_update.setText(_translate("MainWindow", "Update"))
        self.btn_load_visible.setText(_translate("MainWindow", "Load Recent Visible"))
        self.label_5.setText(_translate("MainWindow", "Exposure Time (ms)"))
        self.le_cam2_exp_time.setText(_translate("MainWindow", "0.05"))
        self.label_6.setText(_translate("MainWindow", "Gain (floating)"))
        self.le_cam2_gain.setText(_translate("MainWindow", "1"))
        self.label_18.setText(_translate("MainWindow", "fpa temp [C] 68=Dmg"))
        self.label_19.setText(_translate("MainWindow", "fpa temp [C]"))
        self.label_4.setText(_translate("MainWindow", "Select Camera:"))
        self.label_8.setText(_translate("MainWindow", "Threshold"))
        self.le_cam2_threshold.setText(_translate("MainWindow", "0"))
        self.label_15.setText(_translate("MainWindow", "# of Frames 2 Avg"))
        self.Cam2_AvgFrames.setText(_translate("MainWindow", "1"))
        self.btn_cam2_update.setText(_translate("MainWindow", "Update"))
        self.btn_cam2_gen_ROI.setText(_translate("MainWindow", "Generate ROI"))
        self.btn_cam2_apply_ROI.setText(_translate("MainWindow", "Crop to ROI"))
        self.label_10.setText(_translate("MainWindow", "Max Value"))
        self.le_cam2_max.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "Max Value"))
        self.le_cam1_max.setText(_translate("MainWindow", "0"))
        self.cb_SystemSelection.setItemText(0, _translate("MainWindow", "Select Point Lock System"))
        self.cb_SystemSelection.setItemText(1, _translate("MainWindow", "Visible Point Lock"))
        self.cb_SystemSelection.setItemText(2, _translate("MainWindow", "IR Point Lock"))
        self.pb_cam2_img_cap.setText(_translate("MainWindow", "Capture Cam2 img"))
        self.pb_cam1_img_cap.setText(_translate("MainWindow", "Capture Cam1 img"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_microView), _translate("MainWindow", "Camera View"))
        self.btn_clear.setText(_translate("MainWindow", "Clear"))
        self.label_11.setText(_translate("MainWindow", "# of Points"))
        self.le_num_points.setText(_translate("MainWindow", "100"))
        self.label_cam1_dx_std.setText(_translate("MainWindow", "Cam 1 dx std"))
        self.label_cam1_dy_std.setText(_translate("MainWindow", "Cam 1 dy std"))
        self.label_cam2_dx_std.setText(_translate("MainWindow", "Cam 2 dx std"))
        self.label_cam2_dy_std.setText(_translate("MainWindow", "Cam 2 dy std"))
        self.label_22.setText(_translate("MainWindow", "Data Acquisition Controls:"))
        self.label_23.setText(_translate("MainWindow", "Acquisition Time"))
        self.le_data_acquisition_time.setText(_translate("MainWindow", "[days, hours, mins, secs]"))
        self.cb_acquire_pointing.setText(_translate("MainWindow", "Collect All COM Data"))
        self.cb_acquire_video.setText(_translate("MainWindow", "Acquire Video"))
        self.cb_acquire_voltages.setText(_translate("MainWindow", "Collect All piezo voltage data"))
        self.btn_begin_acquisition.setText(_translate("MainWindow", "Begin Acquisition"))
        self.label_21.setText(_translate("MainWindow", "TextLabel"))
        self.label_fps_t_avg.setText(_translate("MainWindow", "Cam avg. fps for time (s)"))
        self.le_cam_fps_t_avg.setText(_translate("MainWindow", "1"))
        self.label_cam1_fps_read.setText(_translate("MainWindow", "Cam 1 fps (read)"))
        self.label_cam1_fps_processed.setText(_translate("MainWindow", "Cam 1 fps (processed)"))
        self.label_cam2_fps_read.setText(_translate("MainWindow", "Cam 2 fps (read)"))
        self.label_cam2_fps_processed.setText(_translate("MainWindow", "Cam 2 fps (processed)"))
        self.label_processed_def.setText(_translate("MainWindow", "\"processed\" = fps update manager finds COM for"))
        self.label_read_def.setText(_translate("MainWindow", "\"read\" = fps camera object reads at"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Pointing View"))
        self.label_12.setText(_translate("MainWindow", "Motor 1"))
        self.label_13.setText(_translate("MainWindow", "Motor 2"))
        self.btn_motor_connect.setText(_translate("MainWindow", "Connect"))
        self.P.setText(_translate("MainWindow", "P"))
        self.le_P.setText(_translate("MainWindow", "1"))
        self.Ti.setText(_translate("MainWindow", "I"))
        self.Ti_2.setText(_translate("MainWindow", "D"))
        self.le_Td.setText(_translate("MainWindow", "1"))
        self.btn_PID_update.setText(_translate("MainWindow", "Update PID Parameters"))
        self.le_Ti.setText(_translate("MainWindow", "1"))
        self.label_24.setText(_translate("MainWindow", "Select 4 motors for fast control (Regularly updated)"))
        self.label_25.setText(_translate("MainWindow", "Select 2 motors to move when fast motors go out of bounds"))
        self.label_26.setText(_translate("MainWindow", "NOTE: You must rerun calibration if you update these motors to be different than when you last calibrated."))
        self.pb_update_control_motors.setText(_translate("MainWindow", "update control motors"))
        self.label_piezo_updates_per_second.setText(_translate("MainWindow", "Piezo updates/second"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Piezo View"))
        self.label_unlock_report.setText(_translate("MainWindow", "If you are seeing this, there are no attempted piezo updates outside of their allowed range yet.... Good! "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.UnlockReport), _translate("MainWindow", "Unlock Report"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Calibration Controls"))
        self.btn_lock.setText(_translate("MainWindow", "LOCK"))
        self.btn_Home.setText(_translate("MainWindow", "Define New Home"))
        self.btn_Align.setText(_translate("MainWindow", "Align"))
        self.cb_suppress_image_update.setText(_translate("MainWindow", "Suppress GUI Image Update"))
        self.cb_suppress_piezzo_update.setText(_translate("MainWindow", "Suppress GUI Piezzo Update"))
        self.cb_suppress_pointing_updat.setText(_translate("MainWindow", "Suppress GUI Pointing Update"))
        self.cb_force_unlock.setText(_translate("MainWindow", "Force Unlock"))
        self.label_20.setText(_translate("MainWindow", "Time (s) allowed outside of Piezzo range (without getting in bounds for more than 60 s) before forced to unlock (if checked)"))
        self.le_max_unlock_time.setText(_translate("MainWindow", "120"))
        self.menuCalibrate.setTitle(_translate("MainWindow", "File"))
        self.act_calibrate.setText(_translate("MainWindow", "Calibrate"))
        self.actionLoad_Old_Home.setText(_translate("MainWindow", "Load Old Home"))
        self.actionSave_State.setText(_translate("MainWindow", "Save State"))
        self.actionLoad_State.setText(_translate("MainWindow", "Load State"))

from pyqtgraph import GraphicsLayoutWidget, ImageView
