# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pointing_stability.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1067, 713)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 981, 631))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_microView = QtWidgets.QWidget()
        self.tab_microView.setObjectName("tab_microView")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_microView)
        self.formLayoutWidget.setGeometry(QtCore.QRect(740, 40, 221, 173))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.le_cam1_exp_time = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_cam1_exp_time.setObjectName("le_cam1_exp_time")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_cam1_exp_time)
        self.le_cam1_gain = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_cam1_gain.setObjectName("le_cam1_gain")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_cam1_gain)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.btn_cam1_update = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_cam1_update.setObjectName("btn_cam1_update")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.btn_cam1_update)
        self.cb_cam1 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cb_cam1.setEditable(False)
        self.cb_cam1.setObjectName("cb_cam1")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cb_cam1)
        self.cb_cam1_decimate = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.cb_cam1_decimate.setChecked(True)
        self.cb_cam1_decimate.setObjectName("cb_cam1_decimate")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cb_cam1_decimate)
        self.le_cam1_threshold = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_cam1_threshold.setObjectName("le_cam1_threshold")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.le_cam1_threshold)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.gv_camera2 = ImageView(self.tab_microView)
        self.gv_camera2.setGeometry(QtCore.QRect(10, 310, 701, 281))
        self.gv_camera2.setObjectName("gv_camera2")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab_microView)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(740, 330, 221, 173))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.le_cam2_exp_time = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.le_cam2_exp_time.setObjectName("le_cam2_exp_time")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_cam2_exp_time)
        self.le_cam2_gain = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.le_cam2_gain.setObjectName("le_cam2_gain")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_cam2_gain)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.cb_cam2 = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.cb_cam2.setEditable(False)
        self.cb_cam2.setObjectName("cb_cam2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cb_cam2)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.cb_cam2_decimate = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.cb_cam2_decimate.setChecked(True)
        self.cb_cam2_decimate.setObjectName("cb_cam2_decimate")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cb_cam2_decimate)
        self.btn_cam2_update = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.btn_cam2_update.setObjectName("btn_cam2_update")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.btn_cam2_update)
        self.le_cam2_threshold = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.le_cam2_threshold.setObjectName("le_cam2_threshold")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.le_cam2_threshold)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.gv_camera1 = ImageView(self.tab_microView)
        self.gv_camera1.setGeometry(QtCore.QRect(10, 10, 701, 281))
        self.gv_camera1.setObjectName("gv_camera1")
        self.layoutWidget = QtWidgets.QWidget(self.tab_microView)
        self.layoutWidget.setGeometry(QtCore.QRect(790, 520, 131, 24))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.le_cam2_max = QtWidgets.QLineEdit(self.layoutWidget)
        self.le_cam2_max.setReadOnly(True)
        self.le_cam2_max.setObjectName("le_cam2_max")
        self.horizontalLayout_2.addWidget(self.le_cam2_max)
        self.widget = QtWidgets.QWidget(self.tab_microView)
        self.widget.setGeometry(QtCore.QRect(790, 230, 131, 24))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.le_cam1_max = QtWidgets.QLineEdit(self.widget)
        self.le_cam1_max.setReadOnly(True)
        self.le_cam1_max.setObjectName("le_cam1_max")
        self.horizontalLayout.addWidget(self.le_cam1_max)
        self.tabWidget.addTab(self.tab_microView, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gv_cam_xy = GraphicsLayoutWidget(self.tab_2)
        self.gv_cam_xy.setGeometry(QtCore.QRect(20, 10, 701, 581))
        self.gv_cam_xy.setObjectName("gv_cam_xy")
        self.btn_clear = QtWidgets.QPushButton(self.tab_2)
        self.btn_clear.setGeometry(QtCore.QRect(810, 20, 93, 28))
        self.btn_clear.setObjectName("btn_clear")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(780, 60, 141, 31))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.le_num_points = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.le_num_points.setReadOnly(True)
        self.le_num_points.setObjectName("le_num_points")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_num_points)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gv_piezo = GraphicsLayoutWidget(self.tab)
        self.gv_piezo.setGeometry(QtCore.QRect(20, 10, 701, 581))
        self.gv_piezo.setObjectName("gv_piezo")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(740, 10, 160, 80))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_12.setObjectName("label_12")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.cb_motors_1 = QtWidgets.QComboBox(self.formLayoutWidget_4)
        self.cb_motors_1.setObjectName("cb_motors_1")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cb_motors_1)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_13.setObjectName("label_13")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.cb_motors_2 = QtWidgets.QComboBox(self.formLayoutWidget_4)
        self.cb_motors_2.setObjectName("cb_motors_2")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cb_motors_2)
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1067, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.gv_camera1, self.le_cam1_exp_time)
        MainWindow.setTabOrder(self.le_cam1_exp_time, self.le_cam1_gain)
        MainWindow.setTabOrder(self.le_cam1_gain, self.cb_cam1)
        MainWindow.setTabOrder(self.cb_cam1, self.le_cam1_threshold)
        MainWindow.setTabOrder(self.le_cam1_threshold, self.cb_cam1_decimate)
        MainWindow.setTabOrder(self.cb_cam1_decimate, self.btn_cam1_update)
        MainWindow.setTabOrder(self.btn_cam1_update, self.le_cam1_max)
        MainWindow.setTabOrder(self.le_cam1_max, self.le_cam2_exp_time)
        MainWindow.setTabOrder(self.le_cam2_exp_time, self.le_cam2_gain)
        MainWindow.setTabOrder(self.le_cam2_gain, self.cb_cam2)
        MainWindow.setTabOrder(self.cb_cam2, self.le_cam2_threshold)
        MainWindow.setTabOrder(self.le_cam2_threshold, self.cb_cam2_decimate)
        MainWindow.setTabOrder(self.cb_cam2_decimate, self.btn_cam2_update)
        MainWindow.setTabOrder(self.btn_cam2_update, self.le_cam2_max)
        MainWindow.setTabOrder(self.le_cam2_max, self.gv_cam_xy)
        MainWindow.setTabOrder(self.gv_cam_xy, self.btn_clear)
        MainWindow.setTabOrder(self.btn_clear, self.le_num_points)
        MainWindow.setTabOrder(self.le_num_points, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.gv_camera2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mightex Camera"))
        self.label.setText(_translate("MainWindow", "Exposure Time (ms)"))
        self.le_cam1_exp_time.setText(_translate("MainWindow", "0.05"))
        self.le_cam1_gain.setText(_translate("MainWindow", "1"))
        self.label_2.setText(_translate("MainWindow", "Gain (floating)"))
        self.btn_cam1_update.setText(_translate("MainWindow", "Update"))
        self.cb_cam1_decimate.setText(_translate("MainWindow", "Decimation"))
        self.le_cam1_threshold.setText(_translate("MainWindow", "0"))
        self.label_3.setText(_translate("MainWindow", "Select Camera"))
        self.label_7.setText(_translate("MainWindow", "Threshold"))
        self.label_5.setText(_translate("MainWindow", "Exposure Time (ms)"))
        self.le_cam2_exp_time.setText(_translate("MainWindow", "0.05"))
        self.le_cam2_gain.setText(_translate("MainWindow", "1"))
        self.label_6.setText(_translate("MainWindow", "Gain (floating)"))
        self.label_4.setText(_translate("MainWindow", "Select Camera:"))
        self.cb_cam2_decimate.setText(_translate("MainWindow", "Decimation"))
        self.btn_cam2_update.setText(_translate("MainWindow", "Update"))
        self.le_cam2_threshold.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "Threshold"))
        self.label_10.setText(_translate("MainWindow", "Max Value"))
        self.le_cam2_max.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "Max Value"))
        self.le_cam1_max.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_microView), _translate("MainWindow", "Camera View"))
        self.btn_clear.setText(_translate("MainWindow", "Clear"))
        self.label_11.setText(_translate("MainWindow", "# of Points"))
        self.le_num_points.setText(_translate("MainWindow", "100"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Pointing View"))
        self.label_12.setText(_translate("MainWindow", "Motor 1"))
        self.label_13.setText(_translate("MainWindow", "Motor 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Piezo View"))

from pyqtgraph import GraphicsLayoutWidget, ImageView
