# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pointing_stability.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1072, 780)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 981, 631))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_microView = QtWidgets.QWidget()
        self.tab_microView.setObjectName("tab_microView")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_microView)
        self.formLayoutWidget.setGeometry(QtCore.QRect(740, 40, 221, 211))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.le_cam1_exp_time = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_cam1_exp_time.setObjectName("le_cam1_exp_time")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_cam1_exp_time)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.le_cam1_gain = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_cam1_gain.setObjectName("le_cam1_gain")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_cam1_gain)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.cb_cam1 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cb_cam1.setEditable(False)
        self.cb_cam1.setObjectName("cb_cam1")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cb_cam1)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.le_cam1_threshold = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_cam1_threshold.setObjectName("le_cam1_threshold")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.le_cam1_threshold)
        self.cb_cam1_decimate = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.cb_cam1_decimate.setChecked(True)
        self.cb_cam1_decimate.setObjectName("cb_cam1_decimate")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.cb_cam1_decimate)
        self.btn_cam1_update = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_cam1_update.setObjectName("btn_cam1_update")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.btn_cam1_update)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_17)
        self.Cam1_AvgFrames = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.Cam1_AvgFrames.setObjectName("Cam1_AvgFrames")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.Cam1_AvgFrames)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.gv_camera2 = ImageView(self.tab_microView)
        self.gv_camera2.setGeometry(QtCore.QRect(10, 310, 701, 281))
        self.gv_camera2.setObjectName("gv_camera2")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab_microView)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(740, 320, 221, 197))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.le_cam2_exp_time = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.le_cam2_exp_time.setObjectName("le_cam2_exp_time")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_cam2_exp_time)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.le_cam2_gain = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.le_cam2_gain.setObjectName("le_cam2_gain")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_cam2_gain)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.cb_cam2 = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.cb_cam2.setEditable(False)
        self.cb_cam2.setObjectName("cb_cam2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cb_cam2)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.le_cam2_threshold = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.le_cam2_threshold.setObjectName("le_cam2_threshold")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.le_cam2_threshold)
        self.cb_cam2_decimate = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.cb_cam2_decimate.setChecked(True)
        self.cb_cam2_decimate.setObjectName("cb_cam2_decimate")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.cb_cam2_decimate)
        self.btn_cam2_update = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.btn_cam2_update.setObjectName("btn_cam2_update")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.btn_cam2_update)
        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.label_19 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_19)
        self.Cam2_AvgFrames = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.Cam2_AvgFrames.setObjectName("Cam2_AvgFrames")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.Cam2_AvgFrames)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.gv_camera1 = ImageView(self.tab_microView)
        self.gv_camera1.setGeometry(QtCore.QRect(10, 10, 701, 281))
        self.gv_camera1.setObjectName("gv_camera1")
        self.layoutWidget = QtWidgets.QWidget(self.tab_microView)
        self.layoutWidget.setGeometry(QtCore.QRect(790, 540, 131, 24))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.le_cam2_max = QtWidgets.QLineEdit(self.layoutWidget)
        self.le_cam2_max.setReadOnly(True)
        self.le_cam2_max.setObjectName("le_cam2_max")
        self.horizontalLayout_2.addWidget(self.le_cam2_max)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_microView)
        self.layoutWidget1.setGeometry(QtCore.QRect(790, 260, 131, 24))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.le_cam1_max = QtWidgets.QLineEdit(self.layoutWidget1)
        self.le_cam1_max.setReadOnly(True)
        self.le_cam1_max.setObjectName("le_cam1_max")
        self.horizontalLayout.addWidget(self.le_cam1_max)
        self.cb_SystemSelection = QtWidgets.QComboBox(self.tab_microView)
        self.cb_SystemSelection.setGeometry(QtCore.QRect(780, 0, 141, 21))
        self.cb_SystemSelection.setObjectName("cb_SystemSelection")
        self.cb_SystemSelection.addItem("")
        self.cb_SystemSelection.addItem("")
        self.cb_SystemSelection.addItem("")
        self.tabWidget.addTab(self.tab_microView, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gv_cam_xy = GraphicsLayoutWidget(self.tab_2)
        self.gv_cam_xy.setGeometry(QtCore.QRect(20, 10, 701, 581))
        self.gv_cam_xy.setObjectName("gv_cam_xy")
        self.btn_clear = QtWidgets.QPushButton(self.tab_2)
        self.btn_clear.setGeometry(QtCore.QRect(810, 20, 93, 28))
        self.btn_clear.setObjectName("btn_clear")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(780, 60, 141, 31))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.le_num_points = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.le_num_points.setReadOnly(False)
        self.le_num_points.setObjectName("le_num_points")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_num_points)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gv_piezo = GraphicsLayoutWidget(self.tab)
        self.gv_piezo.setGeometry(QtCore.QRect(20, 10, 701, 581))
        self.gv_piezo.setObjectName("gv_piezo")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(740, 10, 160, 88))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_12.setObjectName("label_12")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.cb_motors_1 = QtWidgets.QComboBox(self.formLayoutWidget_4)
        self.cb_motors_1.setObjectName("cb_motors_1")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cb_motors_1)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_13.setObjectName("label_13")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.cb_motors_2 = QtWidgets.QComboBox(self.formLayoutWidget_4)
        self.cb_motors_2.setObjectName("cb_motors_2")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cb_motors_2)
        self.btn_motor_connect = QtWidgets.QPushButton(self.formLayoutWidget_4)
        self.btn_motor_connect.setObjectName("btn_motor_connect")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btn_motor_connect)
        self.tabWidget.addTab(self.tab, "")
        self.btn_lock = QtWidgets.QPushButton(self.centralwidget)
        self.btn_lock.setGeometry(QtCore.QRect(30, 660, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_lock.setFont(font)
        self.btn_lock.setCheckable(True)
        self.btn_lock.setObjectName("btn_lock")
        self.btn_Home = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Home.setGeometry(QtCore.QRect(180, 660, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_Home.setFont(font)
        self.btn_Home.setObjectName("btn_Home")
        self.btn_Align = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Align.setGeometry(QtCore.QRect(330, 660, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_Align.setFont(font)
        self.btn_Align.setObjectName("btn_Align")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(9, 9, 1021, 721))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1019, 719))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea.raise_()
        self.tabWidget.raise_()
        self.btn_lock.raise_()
        self.btn_Home.raise_()
        self.btn_Align.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1072, 21))
        self.menubar.setObjectName("menubar")
        self.menuCalibrate = QtWidgets.QMenu(self.menubar)
        self.menuCalibrate.setObjectName("menuCalibrate")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.act_calibrate = QtWidgets.QAction(MainWindow)
        self.act_calibrate.setObjectName("act_calibrate")
        self.actionLoad_Old_Home = QtWidgets.QAction(MainWindow)
        self.actionLoad_Old_Home.setObjectName("actionLoad_Old_Home")
        self.menuCalibrate.addAction(self.act_calibrate)
        self.menuCalibrate.addAction(self.actionLoad_Old_Home)
        self.menubar.addAction(self.menuCalibrate.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.gv_camera1, self.gv_cam_xy)
        MainWindow.setTabOrder(self.gv_cam_xy, self.gv_piezo)
        MainWindow.setTabOrder(self.gv_piezo, self.le_cam1_exp_time)
        MainWindow.setTabOrder(self.le_cam1_exp_time, self.le_cam1_gain)
        MainWindow.setTabOrder(self.le_cam1_gain, self.cb_cam1)
        MainWindow.setTabOrder(self.cb_cam1, self.le_cam1_threshold)
        MainWindow.setTabOrder(self.le_cam1_threshold, self.cb_cam1_decimate)
        MainWindow.setTabOrder(self.cb_cam1_decimate, self.btn_cam1_update)
        MainWindow.setTabOrder(self.btn_cam1_update, self.le_cam1_max)
        MainWindow.setTabOrder(self.le_cam1_max, self.le_cam2_exp_time)
        MainWindow.setTabOrder(self.le_cam2_exp_time, self.le_cam2_gain)
        MainWindow.setTabOrder(self.le_cam2_gain, self.cb_cam2)
        MainWindow.setTabOrder(self.cb_cam2, self.le_cam2_threshold)
        MainWindow.setTabOrder(self.le_cam2_threshold, self.cb_cam2_decimate)
        MainWindow.setTabOrder(self.cb_cam2_decimate, self.btn_cam2_update)
        MainWindow.setTabOrder(self.btn_cam2_update, self.le_cam2_max)
        MainWindow.setTabOrder(self.le_cam2_max, self.gv_camera2)
        MainWindow.setTabOrder(self.gv_camera2, self.btn_clear)
        MainWindow.setTabOrder(self.btn_clear, self.le_num_points)
        MainWindow.setTabOrder(self.le_num_points, self.cb_motors_1)
        MainWindow.setTabOrder(self.cb_motors_1, self.cb_motors_2)
        MainWindow.setTabOrder(self.cb_motors_2, self.tabWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mightex Camera"))
        self.label.setText(_translate("MainWindow", "Exposure Time (ms)"))
        self.le_cam1_exp_time.setText(_translate("MainWindow", "0.05"))
        self.label_2.setText(_translate("MainWindow", "Gain (floating)"))
        self.le_cam1_gain.setText(_translate("MainWindow", "1"))
        self.label_3.setText(_translate("MainWindow", "Select Camera"))
        self.label_7.setText(_translate("MainWindow", "Threshold"))
        self.le_cam1_threshold.setText(_translate("MainWindow", "0"))
        self.cb_cam1_decimate.setText(_translate("MainWindow", "Decimation"))
        self.btn_cam1_update.setText(_translate("MainWindow", "Update"))
        self.label_16.setText(_translate("MainWindow", "fpa temp [C] 68=Dmg"))
        self.label_17.setText(_translate("MainWindow", "fpa temp [C]"))
        self.Cam1_AvgFrames.setText(_translate("MainWindow", "1"))
        self.label_14.setText(_translate("MainWindow", "# of Frames 2 Avg"))
        self.label_5.setText(_translate("MainWindow", "Exposure Time (ms)"))
        self.le_cam2_exp_time.setText(_translate("MainWindow", "0.05"))
        self.label_6.setText(_translate("MainWindow", "Gain (floating)"))
        self.le_cam2_gain.setText(_translate("MainWindow", "1"))
        self.label_4.setText(_translate("MainWindow", "Select Camera:"))
        self.label_8.setText(_translate("MainWindow", "Threshold"))
        self.le_cam2_threshold.setText(_translate("MainWindow", "0"))
        self.cb_cam2_decimate.setText(_translate("MainWindow", "Decimation"))
        self.btn_cam2_update.setText(_translate("MainWindow", "Update"))
        self.label_18.setText(_translate("MainWindow", "fpa temp [C] 68=Dmg"))
        self.label_19.setText(_translate("MainWindow", "fpa temp [C]"))
        self.Cam2_AvgFrames.setText(_translate("MainWindow", "1"))
        self.label_15.setText(_translate("MainWindow", "# of Frames 2 Avg"))
        self.label_10.setText(_translate("MainWindow", "Max Value"))
        self.le_cam2_max.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "Max Value"))
        self.le_cam1_max.setText(_translate("MainWindow", "0"))
        self.cb_SystemSelection.setItemText(0, _translate("MainWindow", "Select Point Lock System"))
        self.cb_SystemSelection.setItemText(1, _translate("MainWindow", "Visible Point Lock"))
        self.cb_SystemSelection.setItemText(2, _translate("MainWindow", "IR Point Lock"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_microView), _translate("MainWindow", "Camera View"))
        self.btn_clear.setText(_translate("MainWindow", "Clear"))
        self.label_11.setText(_translate("MainWindow", "# of Points"))
        self.le_num_points.setText(_translate("MainWindow", "100"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Pointing View"))
        self.label_12.setText(_translate("MainWindow", "Motor 1"))
        self.label_13.setText(_translate("MainWindow", "Motor 2"))
        self.btn_motor_connect.setText(_translate("MainWindow", "Connect"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Piezo View"))
        self.btn_lock.setText(_translate("MainWindow", "LOCK"))
        self.btn_Home.setText(_translate("MainWindow", "Define New Home"))
        self.btn_Align.setText(_translate("MainWindow", "Align"))
        self.menuCalibrate.setTitle(_translate("MainWindow", "File"))
        self.act_calibrate.setText(_translate("MainWindow", "Calibrate"))
        self.actionLoad_Old_Home.setText(_translate("MainWindow", "Load Old Home"))
from pyqtgraph import GraphicsLayoutWidget, ImageView
